In [1]:
from keras.datasets import imdb
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words = 10000)

17464789/17464789 [==============================] - 0s 0us/step


In [2]:
import numpy as np

def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))    # Creates an all zero matrix of shape (len(sequences),10K)
    for i,sequence in enumerate(sequences):
        results[i,sequence] = 1                        # Sets specific indices of results[i] to 1s
    return results

# Vectorize training Data
X_train = vectorize_sequences(train_data)

# Vectorize testing Data
X_test = vectorize_sequences(test_data)

In [3]:
X_train[0]

array([0., 1., 1., ..., 0., 0., 0.])

In [4]:
X_train.shape

(25000, 10000)

In [5]:
y_train= np.asarray(train_labels).astype('float32')
y_test= np.asarray(test_labels).astype('float32')

In [6]:
from keras import models
from keras import layers

model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [9]:
from keras import optimizers
from keras import losses
from keras import metrics

model.compile(optimizer=optimizers.RMSprop(learning_rate=0.001), loss = losses.binary_crossentropy, metrics = [metrics.binary_accuracy])

In [10]:
# Input for Validation
X_val = X_train[:10000]
partial_X_train = X_train[10000:]

# Labels for validation
y_val = y_train[:10000]
partial_y_train = y_train[10000:]

In [11]:
model.fit(partial_X_train, partial_y_train, epochs=3, batch_size=512, validation_data=(X_val, y_val))

Epoch 1/3
30/30 [==============================] - 4s 96ms/step - loss: 0.5359 - binary_accuracy: 0.7836 - val_loss: 0.4572 - val_binary_accuracy: 0.8313
Epoch 2/3
30/30 [==============================] - 1s 39ms/step - loss: 0.3390 - binary_accuracy: 0.9000 - val_loss: 0.3272 - val_binary_accuracy: 0.8856
Epoch 3/3
30/30 [==============================] - 1s 37ms/step - loss: 0.2475 - binary_accuracy: 0.9238 - val_loss: 0.2905 - val_binary_accuracy: 0.8901


In [12]:
np.set_printoptions(suppress=True)
result = model.predict(X_test)

782/782 [==============================] - 2s 2ms/step


In [13]:
result

array([[0.35043496],
       [0.97421885],
       [0.9620757 ],
       ...,
       [0.13796534],
       [0.2436305 ],
       [0.6367867 ]], dtype=float32)

In [14]:
y_pred = np.zeros(len(result))
for i, score in enumerate(result):
    y_pred[i] = 1 if score > 0.5 else 0

In [15]:
y_pred

array([0., 1., 1., ..., 0., 0., 1.])

In [17]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_pred, y_test)

In [18]:
mae

0.11572

In [19]:
from sklearn.metrics import mean_squared_error
mse= mean_squared_error(y_pred, y_test)

In [20]:
mse

0.11572